spring.application.name=crudbootdemo


# JDBC properties
spring.datasource.url=jdbc:mysql://localhost:3306/schema312?useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8
spring.datasource.username=student
spring.datasource.password=student
server.error.include-stacktrace=always
logging.level.org.springframework.jdbc.core=TRACE
# server.port=8088
spring.jpa.hibernate.ddl-auto=create
roles=user,admin